import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Arya",
    lastName: "Shah",
    username: "aryashah",
    password: "aryashah123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/1.jpg",
    status:"Amazing",

  },
  {
    _id: uuid(),
    firstName: "Joey",
    lastName: "Tribbiani",
    username: "joey",
    password: "joey123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/1.jpg",
    status:"Joey doesn't share food!",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Chandler",
    lastName: "Bing",
    username: "chandler",
    password: "chandler123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/1.jpg",
    status:"Hi, I'm Chandler. I make jokes when I'm uncomfortable.",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Phoebe",
    lastName: "Buffay",
    username: "phoebe",
    password: "phoebe123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/1.jpg",
    status:"I wish I could, but I don't want to.",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Ross",
    lastName: "Geller",
    username: "ross",
    password: "ross123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/1.jpg",
    status:"Unagi Is A Total State Of Awareness.",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Monica",
    lastName: "Geller",
    username: "monica",
    password: "monica123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/5.jpg",
    status:"I'm the boss of this kitchen!",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Rachel",
    lastName: "Green",
    username: "rachel",
    password: "rachel123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://randomuser.me/api/portraits/men/2.jpg",
    status:"Okay Hi.",
    followers:[],
    following:[],
    bookmarks:[],
  },
  {
    _id: uuid(),
    firstName: "Bad",
    lastName: "Girl",
    username: "badgirl",
    password: "badgirl123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    profilePic:"https://cataas.com/cat?type=sq",
    status:"I will find you and ignore you.",
    followers:[],
    following:[],
    bookmarks:[],
  },
];
